# Stage 1 - Build react app
FROM node:latest as build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
#RUN npm run build

# Stage 2 - Serve react app with nginx
#FROM nginx:alpine
#COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3000
