version: '2.24.6'
services:
  mysql:
    container_name: mysql-cn
    image: mysql:8 
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - spring-net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gestion_ca
  backend:
    image: hossamchalabi/repo:latest
    ports:
      - 8080:8080
    networks:
      - spring-net
    depends_on:
      - mysql
  react_app:
    container_name: react_app
    image: getiteasy/frontend
    volumes:
      - ./front_admin/src:/react/src:ro
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend
        

    
volumes:
  db_data: {}

networks:
  spring-net:
    driver: bridge
