---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: getiteasy/frontend
        command: ["npm", "start"]
        volumeMounts:
        - name: source-code
          mountPath: /react/src
        ports:
        - containerPort: 3000
      volumes:
      - name: source-code
        hostPath:
          path: ./front_admin/src
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend